<?php
$data = array (
  0 => 
  array (
    'cat_id' => '32',
    'cat_name' => '领养一只猫咪',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  1 => 
  array (
    'cat_id' => '27',
    'cat_name' => '喵星人生活馆',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '3',
    'sort_order' => '20',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  2 => 
  array (
    'cat_id' => '38',
    'cat_name' => '蓝星人主题馆',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '30',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  3 => 
  array (
    'cat_id' => '42',
    'cat_name' => '帮助身边的流浪猫',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '40',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  4 => 
  array (
    'cat_id' => '45',
    'cat_name' => '土猫团购',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  5 => 
  array (
    'cat_id' => '28',
    'cat_name' => '主食',
    'measure_unit' => '',
    'parent_id' => '27',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '3',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  6 => 
  array (
    'cat_id' => '29',
    'cat_name' => '零食/营养品',
    'measure_unit' => '',
    'parent_id' => '27',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '3',
    'sort_order' => '20',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  7 => 
  array (
    'cat_id' => '30',
    'cat_name' => '玩具',
    'measure_unit' => '',
    'parent_id' => '27',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '30',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  8 => 
  array (
    'cat_id' => '37',
    'cat_name' => '猫砂',
    'measure_unit' => '',
    'parent_id' => '27',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '30',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  9 => 
  array (
    'cat_id' => '31',
    'cat_name' => '生活用品',
    'measure_unit' => '',
    'parent_id' => '27',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '40',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  10 => 
  array (
    'cat_id' => '39',
    'cat_name' => '成年猫',
    'measure_unit' => '',
    'parent_id' => '32',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  11 => 
  array (
    'cat_id' => '40',
    'cat_name' => '幼猫',
    'measure_unit' => '',
    'parent_id' => '32',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  12 => 
  array (
    'cat_id' => '34',
    'cat_name' => '家居用品',
    'measure_unit' => '',
    'parent_id' => '38',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  13 => 
  array (
    'cat_id' => '36',
    'cat_name' => '服饰鞋帽',
    'measure_unit' => '',
    'parent_id' => '38',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  14 => 
  array (
    'cat_id' => '35',
    'cat_name' => '玻璃瓷器',
    'measure_unit' => '',
    'parent_id' => '38',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '30',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  15 => 
  array (
    'cat_id' => '41',
    'cat_name' => '杂货铺',
    'measure_unit' => '',
    'parent_id' => '38',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '40',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  16 => 
  array (
    'cat_id' => '43',
    'cat_name' => '群护猫粮',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  17 => 
  array (
    'cat_id' => '44',
    'cat_name' => '绝育优惠',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '0',
    'goods_num' => 0,
  ),
);
?>